# Generated by Django 5.1.2 on 2024-10-29 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "投票",
            },
        ),
        migrations.CreateModel(
            name="VoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="upload/vote/")),
                ("count", models.IntegerField(default=0)),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.vote"
                    ),
                ),
            ],
            options={
                "db_table": "投票项",
            },
        ),
    ]
