# Generated by Django 5.1.2 on 2024-10-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vote",
            table="vote",
        ),
        migrations.AlterModelTable(
            name="voteitem",
            table="vote_item",
        ),
    ]
