# Generated by Django 5.1.2 on 2024-10-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_vote_table_alter_voteitem_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vote",
            options={"verbose_name": "投票主题", "verbose_name_plural": "投票主题"},
        ),
        migrations.AlterModelOptions(
            name="voteitem",
            options={"verbose_name": "投票名称", "verbose_name_plural": "投票列表"},
        ),
        migrations.AddField(
            model_name="vote",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="upload/vote/"),
        ),
        migrations.AlterField(
            model_name="voteitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="upload/vote/"),
        ),
    ]
