# Generated by Django 5.1.2 on 2024-10-29 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_vote_options_alter_voteitem_options_vote_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vote_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.voteitem"
                    ),
                ),
            ],
            options={
                "unique_together": {("ip_address", "vote_item")},
            },
        ),
    ]
