# Generated by Django 5.1.2 on 2024-10-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_voterecord_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together=set(),
        ),
    ]
