# Generated by Django 5.1.2 on 2024-10-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_voterecord_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterecord",
            name="ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0"),
        ),
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together={("vote_item", "ip_address", "created_at")},
        ),
    ]
