# Generated by Django 5.1.2 on 2024-11-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_voterecord_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voterecord",
            options={"verbose_name": "投票记录", "verbose_name_plural": "投票记录"},
        ),
        migrations.AlterModelTable(
            name="voterecord",
            table="vote_record",
        ),
    ]
